name = "ai-image-gen"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "IMAGES_BUCKET"
id = "b7b63d1c7a314cb1b76b7788cc92a43c"
